default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'courses_development' %>

test:
  <<: *default
  database: 'courses_test'

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'courses_production' %>